name: EVA-ADDENDUM-BACKEND

on:
    push:
      branches:
        - main
      paths:
        - 'root-platform/**'
        - 'workers/**'
        - template.yaml
        - './github/**'

jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - uses: aws-actions/setup-sam@v1
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - run: sam build --use-container

        # sam deploy
        - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name eva-addendum-serverless --capabilities CAPABILITY_IAM --region us-east-1
